In [1]:
import time
a = range(100000)
b = range(100000)
print(type(a))
print(type(b))

<class 'range'>
<class 'range'>


In [8]:
import time
a = range(100000)
b = range(100000)
print(type(a))
print(type(b))
start = time.time()
c = []
for x,y in zip(a,b):
  su = x+y
  c.append(su)
end = time.time()
print('Total time taken :',(end - start)*1000)

<class 'range'>
<class 'range'>
Total time taken : 49.974679946899414


In [58]:
import numpy as np
import time
a = range(100000)
b = range(100000)
print(type(a))
print(type(b))
arr_1 = np.array(a)
arr_2 = np.array(b)
start = time.time()
arr_3 = arr_1 + arr_2
end = time.time()
print('Total time taken :',(end - start)*1000)



<class 'range'>
<class 'range'>
Total time taken : 0.0


In [59]:
a = np.array([1,2,3,4,5])

In [60]:
a.ndim #to get the dimension of the array

1

In [61]:
a.shape

(5,)

In [62]:
a.dtype # to get the datatype

dtype('int64')

In [63]:
type(a)

numpy.ndarray

In [64]:
b = np.array([[1,2,3,4,5], [6, 7, 8, 9, 10]])

In [65]:
b.ndim

2

In [66]:
b.shape

(2, 5)

In [67]:
b.dtype

dtype('int64')

In [68]:
type(b)

numpy.ndarray

In [69]:
print(list(range(1,11)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [70]:
arr3 = np.arange(5,21)
print(arr3)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [71]:
arr3.reshape(4,4)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [72]:
arr3.reshape(2,8)

array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20]])

In [73]:
arr3.reshape(8,2)

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [74]:
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [75]:
arr[7:13]

array([ 7,  8,  9, 10, 11, 12])

In [76]:
arr[7]

np.int64(7)

In [77]:
arr1 = np.array([4,1,9,3,7,3,2])
print(arr1)

[4 1 9 3 7 3 2]


In [78]:
arr2 = np.array([[-7,5,-2,4],[5,2,7,3],[10,-13,-3,5]])
print(arr2)

[[ -7   5  -2   4]
 [  5   2   7   3]
 [ 10 -13  -3   5]]


In [79]:
arr2.shape

(3, 4)

In [80]:
arr2[2]

array([ 10, -13,  -3,   5])

In [81]:
arr2[1,2]

np.int64(7)

In [82]:
arr2[[1,2]]

array([[  5,   2,   7,   3],
       [ 10, -13,  -3,   5]])

In [83]:
arr2[:,1]

array([  5,   2, -13])

In [84]:
arr2[2]

array([ 10, -13,  -3,   5])

In [85]:
arr2[1:3,1:3]

array([[  2,   7],
       [-13,  -3]])

In [86]:
arr3 = np.arange(10,82,2).reshape(6,6)
print(arr3)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [87]:
arr3[:, [0,3]] # if u want to see the column of the index 0 and 3

array([[10, 16],
       [22, 28],
       [34, 40],
       [46, 52],
       [58, 64],
       [70, 76]])

In [88]:
arr3[:,[1,5]]

array([[12, 20],
       [24, 32],
       [36, 44],
       [48, 56],
       [60, 68],
       [72, 80]])

In [89]:
arr3[:2,:] #first two rows

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [91]:
arr3[2]

array([34, 36, 38, 40, 42, 44])

In [93]:
arr3.sum()

np.int64(1620)

In [95]:
np.mean(arr3)

np.float64(45.0)

In [102]:
arr3.mean(axis = 1)

array([15., 27., 39., 51., 63., 75.])

In [105]:
x_abs = np.abs(arr3)
print(x_abs)

[[10 12 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]


In [107]:
x_mean = np.mean(arr3)
print(x_mean)

45.0


In [108]:
x_std = np.std(arr3)
print(x_std)

20.77658938966323


In [109]:
x_var = np.var(arr3)
print(x_var)

431.6666666666667


In [115]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)
C = A.dot(B)
print(C)

[[28 34]
 [76 98]]


In [121]:
a = np.zeros((5,6))
b = np.ones((5,6))

In [122]:
np.vstack((a,b)) # for vertical stacking

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [123]:
np.hstack((a,b))

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [125]:
np.concatenate((a,b),axis = 1)

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])

In [127]:
np.concatenate((a,b))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])